"""
Quick start example for Azure MusicGen Tools.
This script demonstrates the complete pipeline from loop extraction to model training.
"""
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

print("=" * 80)
print("Azure MusicGen Tools - Quick Start Guide")
print("=" * 80)
print()

print("🚀 COMPLETE WORKFLOW")
print("-" * 80)
print()

print("Step 0: Deploy Azure Infrastructure")
print("  Linux/Mac:  ./arm-templates/deploy.sh")
print("  Windows:    arm-templates\\deploy.bat")
print("  Time: ~10-15 minutes")
print("  Cost: Free (creates resources, no usage yet)")
print()

print("Step 1: Upload Audio Files")
print("  az storage blob upload-batch \\")
print("    --account-name <storage-account> \\")
print("    --destination audio-input \\")
print("    --source /path/to/audio/files")
print("  Time: ~5 minutes")
print("  Cost: Storage only (~$0.02/GB/month)")
print()

print("Step 2: Extract 4-Bar Loops")
print("  python config/submit_loop_extraction_job.py")
print("  Time: ~30 minutes for 1GB of audio")
print("  Cost: ~$0.05 (CPU compute)")
print()

print("Step 3: Train MusicGen with LoRA")
print("  python config/submit_musicgen_training_job.py")
print("  Time: ~2-4 hours (10 epochs)")
print("  Cost: ~$9-12 (GPU compute)")
print()

print("Step 4: Deploy Model for Inference")
print("  python config/deploy_to_azureml.py \\")
print("    --model-path ./model \\")
print("    --endpoint-name musicgen-endpoint")
print("  Time: ~10-15 minutes")
print("  Cost: ~$0.126/hour when running (auto-scales to $0 when idle)")
print()

print("Step 5: Generate Music!")
print("  python examples/generate_music_client.py \\")
print("    --endpoint-uri <your-endpoint> \\")
print("    --api-key <your-key> \\")
print('    --prompt "upbeat electronic music" \\')
print("    --output my_song.wav")
print("  Time: ~10 seconds per song")
print("  Cost: ~$0.001 per request")
print()

print("=" * 80)
print("💰 COST SUMMARY")
print("=" * 80)
print()
print("One-time setup (complete pipeline):    ~$16")
print("Monthly idle cost (keeping resources): ~$7")
print("Per music generation request:          ~$0.001")
print()
print("VS Hugging Face Inference:")
print("  Azure ML:           $0.126/hour  (80% cheaper!)")
print("  Hugging Face:       $0.60/hour+")
print()

print("=" * 80)
print("📚 DETAILED GUIDES")
print("=" * 80)
print()
print("Full deployment guide:      DEPLOYMENT_GUIDE.md")
print("ARM template details:       arm-templates/README.md")
print("Client examples:            examples/README.md")
print("Main documentation:         README.md")
print()

print("=" * 80)
print("🎵 EXAMPLE PROMPTS TO TRY")
print("=" * 80)
print()
print('- "upbeat electronic dance music with heavy bass"')
print('- "classical piano piece in minor key"')
print('- "smooth jazz with saxophone and drums"')
print('- "ambient atmospheric soundscape"')
print('- "80s synthwave with retro drums"')
print('- "acoustic guitar folk song"')
print()

print("=" * 80)
print("⚡ QUICK COMMANDS")
print("=" * 80)
print()
print("Check deployment status:")
print("  az resource list --resource-group musicgen-rg --output table")
print()
print("Monitor training job:")
print("  Visit: https://ml.azure.com")
print()
print("Get endpoint credentials:")
print("  az ml online-endpoint get-credentials \\")
print("    --name musicgen-endpoint \\")
print("    --resource-group musicgen-rg \\")
print("    --workspace-name <workspace-name>")
print()
print("Delete all resources (cleanup):")
print("  az group delete --name musicgen-rg --yes")
print()

print("=" * 80)
print("Ready to start? Run: ./arm-templates/deploy.sh")
print("=" * 80)

