name: musicgen-inference-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - torch>=2.0.0
    - transformers>=4.35.0
    - scipy>=1.10.0
    - numpy>=1.24.0
    - soundfile>=0.12.1
